apiVersion: v1
kind: Service
metadata:
  name: {{ appname }}
  labels:
    app: {{ appname }}
    tier: app
  namespace: {{ namespace }}
spec:
  ports:
  - name: "app"
    port: 8000
    targetPort: 8000
  - name: "celery"
    port: 8001
    targetPort: 8001
  - name: "supervisor"
    port: 9001
    targetPort: 9001
  selector:
    app: {{ appname }}
